common/models/User.php
<?php

namespace common\models;
use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 * @property string $new_password
 */
/**
 * {@inheritdoc}
 */
class User  extends ActiveRecord implements IdentityInterface
{
	const STATUS_DELETED = 0;
	const STATUS_ACTIVE = 1;
	public $loginUrl = ['user/login'];
    public $new_password;
    public $delete_permissions;
    public $add_permissions;
	public static function tableName()
	{
		return '{{%user}}';
	}
	public function rules()
	{
		return [
		    [['new_password','updated_at','delete_permissions','add_permissions','created_at','updated_at'],'safe'],
			['status', 'default', 'value' => self::STATUS_ACTIVE],
			['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
			[['id'], 'exist', 'skipOnError' => true, 'targetClass' => UserPersonalInfo::className(), 'targetAttribute' => ['id' => 'user_id']],
		];
	}
	/**
	 * {@inheritdoc}
	 */
	public function behaviors()
	{
		return [
			TimestampBehavior::className(),
		];
	}



//	public function beforeSave($insert)
//
//	{
//
//		if (parent::beforeSave($insert)) {
//
//			if ($this->newPassword){
//
//				$this->PasswordHash = Yii::$app->getSecurity()->generatePasswordHash($this->newPassword);
//
//            return true;
//			}
//			return false;
//        }
//	}
	public static function getUserRole($user_id)
	{
		return Yii::$app->authManager->getRolesByUser($user_id);
	}
	public function getAuthAssignments()
	{
		return $this->hasMany(AuthAssignment::className(), ['user_id' => 'id']);
	}
	public function getuser()
	{
		return $this->hasMany(BlogPost::className(), ['author_id' => 'id']);
	}
	public function getPersonalInfo(){
		return $this->hasOne(UserPersonalInfo::className(), ['user_id' => 'id']);
	}

	/**
	 * {@inheritdoc}
	 */
	public static function findIdentity($id)
	{
		return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
	}


	/**
	 * {@inheritdoc}
	 */
	public static function findIdentityByAccessToken($token, $type = null)
	{
		return static::findOne(['auth_key' => $token]);
		throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
	}


	/**
	 * Finds user by username
	 *
	 * @param string $username
	 * @return static|null
	 */
	public static function findByUsername($username)
	{
		return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
	}
	public static function findByID($id)
	{
		return static::findOne(['id' => $id]);
	}

	/**
	 * Finds user by password reset token
	 *
	 * @param string $token password reset token
	 * @return static|null
	 */
	public static function findByPasswordResetToken($token)
	{
		if (!static::isPasswordResetTokenValid($token)) {
			return null;
		}

		return static::findOne([
			'password_reset_token' => $token,
			'status' => self::STATUS_ACTIVE,
		]);
	}
	/**
	 * Finds out if password reset token is valid
	 *
	 * @param string $token password reset token
	 * @return bool
	 */
	public static function isPasswordResetTokenValid($token)
	{
		if (empty($token)) {
			return false;
		}

		$timestamp = (int) substr($token, strrpos($token, '_') + 1);
		$expire = Yii::$app->params['user.passwordResetTokenExpire'];
		return $timestamp + $expire >= time();
	}

	/**
	 * {@inheritdoc}
	 */
	public function getId()
	{
		return $this->getPrimaryKey();
	}

	/**
	 * {@inheritdoc}
	 */
	public function getAuthKey()
	{
		return $this->auth_key;
	}

	/**
	 * {@inheritdoc}
	 */
	public function validateAuthKey($authKey)
	{
		return $this->getAuthKey() === $authKey;
	}

	/**
	 * Validates password
	 *
	 * @param string $password password to validate
	 * @return bool if password provided is valid for current user
	 */
	public function validatePassword($password)
	{
		return Yii::$app->security->validatePassword($password, $this->password_hash);
	}
	/**
	 * Generates password hash from password and sets it to the model
	 *
	 * @param string $password
	 */
	public function setPassword($password)
	{
		$this->password_hash = Yii::$app->security->generatePasswordHash($password);
	}
	/**
	 * Generates "remember me" authentication key
	 */
	public function generateAuthKey()
	{
		$this->auth_key = Yii::$app->security->generateRandomString();
	}
	/**
	 * Generates new password reset token
	 */
	public function generatePasswordResetToken()
	{
		$this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
	}
	/**
	 * Removes password reset token
	 */
	public function removePasswordResetToken()
	{
		$this->password_reset_token = null;
	}
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use common\models\AddRoleForm;
use common\models\AuthItem;
use common\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use common\models\LoginForm;
use common\models\PasswordResetRequestForm;
use common\models\ResetPasswordForm;
use common\models\SignupForm;
use common\models\AuthAssignment;
use yii\base\InvalidParamException;
use yii\web\NotFoundHttpException;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
use common\models\EmailSettings;
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup','dashboard','update','delete','unlink'],
                'rules' => [
	                [
		                'actions' => ['signup','dashboard','update','delete','unlink'],
		                'allow' => true,
		                'roles' => ['admin'],
	                ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
	                'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionDashboard()
    {
	    $users=  User::find()->andWhere(['status' => '1'])->all();

	    $signup = new SignupForm();
        $email_settings = EmailSettings::find()->one();
	    if ($signup->load(Yii::$app->request->post())) {
		    if ($user = $signup->signup()) {

               if(isset($email_settings->new_user_email) && $email_settings->new_user_email == 1) {
                    $email ="giurgiu_dan94@yahoo.com";
                   $variables = array("first_name"=>$signup->first_name,"last_name"=>$signup->last_name,"email"=>$signup->email,"username"=>$signup->username,"password"=>$signup->password,"role"=>implode(',',$signup->permissions));
                   $message=Yii::$app->HelperComponent->template_substitution($email_settings->new_user_message,$variables);
                   Yii::$app->HelperComponent->sendEmail($email, $signup->email, 'You have a new account at medical app', $message);
                    Yii::$app->session->setFlash('success', "New user created successfully");
                }
			    if (Yii::$app->getUser()->login($user)) {
				    return $this->goHome();
			    }
		    }
	    }
	    $role = new AddRoleForm();
	    if ($role->load(Yii::$app->request->post())) {
		    if ($user = $role->addrole()) {
			   // if (Yii::$app->getUser()->login($role)) {
				    return $this->goHome();
			   // }
		    }
	    }
	    $roles = AuthItem::find()->all();
	    $users_deactivated =  User::find()->andWhere(['status' => '0'])->all();
        return $this->render('dashboard',['users'=>$users,'signup'=>$signup,'role'=>$role,'roles'=>$roles,'users_deactivated'=>$users_deactivated]);
    }

    public function actionUpdate($id)
    {
    	$model = $this->find($id);
	    $current_user_permissions = $model->authAssignments;
	   // $current_user_permissions =new yii\rbac\ManagerInterface::getRolesByUser($id);
	    $all_permissions = AuthItem::find()->all();

		$request = Yii::$app->request->post('User');
	    if ($request){
		    $model->updated_at = date('Y-m-d h:m:s');
		    if($request['username'] !== $model->username) {
			    $model->username = $request['username'];
		    }

            if($request['email'] !== $model->email) {
	            $model->email = $request['email'];
            }
            if(!empty($request['new_password'])) {
	            $model->setPassword($request['new_password']);
	            $model->generateAuthKey();
            }
            if(!empty($request['delete_permissions'])) {
	            foreach ($request['delete_permissions'] as $item2 => $val) {
	            	$this->actionRevoke($val,$id);
	            }
            }
		    if(!empty($request['add_permissions'])) {
			    foreach ($request['add_permissions'] as $val) {
				    $newPermission = new AuthAssignment;
				    $newPermission->user_id = $id;
				    $newPermission->item_name = $val;
				    $newPermission->save();
			    }
		    }
          if($model->save()) {
	          return $this->redirect(['dashboard']);
          }
	    }
	    return $this->render('update', [
		    'model' => $model,
		    'current_user_permissions'=>$current_user_permissions,
		    'all_permissions'=>$all_permissions,
	    ]);
    }
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }
	public function actionRevoke($role, $userid) {
		$auth = Yii::$app->authManager;

		$rol= $auth->getRole($role);
		if (empty($rol)) {throw new NotFoundHttpException("There is no assignment ".$role." for user ".$userid.".");}

		$res = $auth->revoke($rol, $userid);
		if (!$res) {Yii::$app->session->setFlash('danger', Yii::t("yii", "Error"));}
		return $this->redirect(['dashboard']);
		}

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

	public function actionSignup()
	{
		$model = new SignupForm();
		$authItems = AuthItem::find()->all();
        $email_settings = EmailSettings::find()->one();
		if ($model->load(Yii::$app->request->post())) {
			if ($user = $model->signup()) {

                if(isset($email_settings->new_user_email) && $email_settings->new_user_email == 1) {
                    $email ="giurgiu_dan94@yahoo.com";
                    $variables = array("first_name"=>$model->first_name,"last_name"=>$model->last_name,"email"=>$model->email,"username"=>$model->username,"password"=>$model->password,"role"=>implode(',',$model->permissions));
                    $message=Yii::$app->HelperComponent->template_substitution($email_settings->new_user_message,$variables);
                    Yii::$app->HelperComponent->sendEmail($email, $model->email, 'You have a new account at medical app', $message);
                    Yii::$app->session->setFlash('success', "New user created successfully");
                }
				if (Yii::$app->getUser()->login($user)) {
					return $this->goHome();
				}
			}
		}

		return $this->render('signup', [
			'model' => $model,
			'authItems'=>$authItems,
		]);
	}
	/**
	 * Requests password reset.
	 *
	 * @return mixed
	 */
	public function actionRequestPasswordReset()
	{
		$model = new PasswordResetRequestForm();
		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			if ($model->sendEmail()) {
				Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

				return $this->goHome();
			} else {
				Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
			}
		}

		return $this->render('requestPasswordResetToken', [
			'model' => $model,
		]);
	}
	/**
	 * Resets password.
	 *
	 * @param string $token
	 * @return mixed
	 * @throws BadRequestHttpException
	 */
	public function actionResetPassword($token)
	{
		try {
			$model = new ResetPasswordForm($token);
		} catch (InvalidParamException $e) {
			throw new BadRequestHttpException($e->getMessage());
		}

		if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
			Yii::$app->session->setFlash('success', 'New password saved.');

			return $this->goHome();
		}

		return $this->render('resetPassword', [
			'model' => $model,
		]);
	}
	public function actionDelete($id)
	{
		$this->find($id)->delete();

		return $this->redirect(['dashboard']);
	}
	public function actionUnlink($id)
	{
		$model =$this->find($id);
		$model->status = 0;
		if($model->save()) {
			return $this->redirect(['dashboard']);
		}
	}
	public function actionActivate($id)
	{
		$model =$this->find($id);
		$model->status = 1;
		if($model->save()) {
			return $this->redirect(['dashboard']);
		}
	}
    public function find($id){
        $model = User::findOne($id);
        if($model === null){
            throwException('400', 'Model not exists');
        }
        return $model;
    }
}

backend/views/user/dashboard.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;

use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\bootstrap\Modal;
$this->title = 'Dashboard';
$this->params['breadcrumbs'][] = $this->title;
?>
<style>
    .dasboardtable th, .dasboardtable td {
        border: 1px solid #AAAAAA;
        padding: 3px 2px;
    }
</style>
<div class="dashboard-index">

	<div class="body-content">

		<div class="row">
			<h1>DashBoard</h1>
            <h4>Active users</h4>
            <table class="dasboardtable">
                <tr>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Update</th>
                    <th>Unlink</th>
                    <th>Delete</th>
                </tr>
           <?php

           foreach ($users as $user){
               ?>


                   <tr>
                       <td><?php echo $user->personalInfo['id'];?></td>
                       <td><?php echo $user->personalInfo['first_name'];?></td>
                       <td><?php echo $user->personalInfo['last_name'];?></td>
                       <td><?php  echo $user->username; ?></td>
                       <td><?php  echo $user->email;  ?></td>
                       <td><?php  echo Html::a('Update', ['update', 'id' => $user->id], ['class' => 'btn btn-primary']); ?></td>
                       <td><?php echo Html::a('Unlink', ['unlink', 'id' => $user->id], ['class' => 'btn btn-danger', 'data' => ['confirm' => 'Are you sure you want to deactivate this user?', 'method' => 'post',],]); ?></td>
                       <td><?php  echo Html::a('Delete', ['delete', 'id' => $user->id], ['class' => 'btn btn-danger', 'data' => ['confirm' => 'Are you sure you want to delete this user?', 'method' => 'post',],]); ?></td>
                   </tr>

            <?php
           }
           ?>
            </table>
		</div>
        <div class="row">
         <h4>Deactivated users</h4>
            <table class="dasboardtable">
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Update</th>
                    <th>Activate</th>
                    <th>Delete</th>
                </tr>
		<?php
		foreach ($users_deactivated as $user_dez){
        ?>

                   <tr>
                       <td><?php echo $user_dez->personalInfo['first_name'];?></td>
        <td><?php echo $user_dez->personalInfo['last_name'];?></td>
        <td><?php  echo $user_dez->username; ?></td>
        <td><?php  echo $user_dez->email;  ?></td>
        <td><?php  echo Html::a('Update', ['update', 'id' => $user_dez->id], ['class' => 'btn btn-primary']); ?></td>
        <td><?php echo  Html::a('Activate User', ['activate', 'id' => $user_dez->id], ['class' => 'btn btn-danger', 'data' => ['confirm' => 'Are you sure you want to activate this user?', 'method' => 'post',],]); ?></td>
        <td><?php  echo Html::a('Delete', ['delete', 'id' => $user_dez->id], ['class' => 'btn btn-danger', 'data' => ['confirm' => 'Are you sure you want to delete this user?', 'method' => 'post',],]); ?></td>
        </tr>


        <?php } ?>
        </div>
        </table>
        <br/>
        <br/>
        <div>
            <button class="btn btn-primary" type="button" data-toggle="collapse"  data-target="#newuser" aria-expanded="false" aria-controls="collapseExample">
               Add new User
            </button>
            <div class="collapse" id="newuser">
                <div class="card card-body">
                    <?php
                    //Yii::info("here start",'my_category');
                    echo Yii::$app->controller->renderPartial('signup',array('model'=>$signup,'authItems'=>$roles));
                    ?>
                </div>
            </div>
        </div>
        <br/>
        <div>
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#newrole" aria-expanded="false" aria-controls="collapseExample">
                Add new Role
            </button>
            <div class="collapse" id="newrole">
                <div class="card card-body">
					<?php
					//Yii::info("here start",'my_category');
					echo Yii::$app->controller->renderPartial('role',array('model'=>$role));
					?>
                </div></div>
        </div>
	</div>
</div>

backend/views/user/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
			<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

			<?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

			<?= $form->field($model, 'password')->passwordInput() ?>

			<?= $form->field($model, 'rememberMe')->checkbox() ?>

            <div style="color:#999;margin:1em 0">
                If you forgot your password you can <?= Html::a('reset it', ['user/request-password-reset']) ?>.
            </div>

            <div class="form-group">
				<?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>

			<?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/user/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/user/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/user/role.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 10/29/2018
 * Time: 9:37 PM
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->params['breadcrumbs'][] = ['label' => 'Roles', 'url' => ['index']];
?>
<div class="role-create">

	<h1><?= Html::encode($this->title) ?></h1>

	<div class="role-form">

		<?php $form = ActiveForm::begin([
				'id'=>'role-form',
				'enableClientValidation' => true,
				'options' => [
					'validateOnBlur' => true,
					'class' => 'form'
				]
            ]); ?>

		<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

		<?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

<!--		--><?//= $form->field($model, 'user_id')->hiddenInput(['value'=>Yii::$app->user->id])->label(false) ?>
<!--		--><?php
//		if (\Yii::$app->user->can('admin')) {
//			echo $form->field($model, 'user_id')->dropDownList(\yii\helpers\ArrayHelper::map(\common\models\User::find()->all(), 'id', 'username'), ['class' => 'form-control']);
//		}
		?>
		<div class="form-group">
			<?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
		</div>

		<?php ActiveForm::end(); ?>

	</div>

</div>

backend/views/user/roleview.php
<?php

/* @var $this yii\web\View */

$this->title = 'Dashboard';
?>
<div class="role_view-index">

	<div class="body-content">

		<div class="row">
			<h1>All roles</h1>
			<?php
			foreach ($roles as $role2){
				print_r($role2->name);
				echo ' ';
				print_r($role2->type);
				echo ' ';
				print_r($role2->description);
				echo '<br/>';
			}
			?>
		</div>

	</div>
</div>

backend/views/user/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use common\widgets\ckeditor\CKEditor;
$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">


    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin([
                'id' => 'form-signup',
                'enableClientValidation' => true,
                'options'=>[
                        'enctype'=>'multipart/form-data',
                        'validateOnBlur' => true,
                        'class' => 'form'
                ]
            ]);?>
                <?= $form->field($model, 'username')->textInput(['autofocus' => 'true']);  ?>

                <?= $form->field($model, 'email'); ?>

                <?= $form->field($model, 'password')->passwordInput(); ?>
            <?php $authItemsArray = ArrayHelper::map($authItems,'name','name'); ?>
            <?= $form->field($model, 'permissions')->checkboxList($authItemsArray); ?>

	        <?= $form->field($model, 'first_name')->textInput();  ?>
	        <?= $form->field($model, 'last_name')->textInput();  ?>
	        <?= $form->field($model, 'phone')->textInput();  ?>
	        <?= $form->field($model, 'speciality')->textInput();  ?>
	        <?= $form->field($model, 'avatar')->fileInput();  ?>
	        <?= $form->field($model, 'created_at')->hiddenInput(['value'=>date('d-m-y')])->label(false); ?>
	        <?= $form->field($model, 'updated_at')->hiddenInput(['value'=>date('d-m-y')])->label(false); ?>

            <?= $form->field($model, 'about')->widget(CKEditor::className(), [
                'options' => ['rows' => 6],
                'preset' => 'full'
            ]); ?>

                <div class="form-group">
                    <?= Html::submitButton(Yii::t('app','Signup'), ['class' => 'btn btn-primary', 'name' => 'signup-button']); ?>
                </div>

            <?php ActiveForm::end();?>
        </div>
    </div>
</div>

backend/views/user/update.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Update User: ' . $model->personalInfo['first_name'];

?>
<div class="user-update">
	<h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id'=>'user-update-form',
        'enableClientValidation' => true,
	    'options' => [
            'enctype'=>'multipart/form-data',
		    'validateOnBlur' => true,
		    'class' => 'form'
	    ]]);?>
    <?= $form->field($model, 'username')->textInput(['autofocus' => 'true']);  ?>

    <?= $form->field($model, 'email'); ?>

    <?= $form->field($model, 'new_password')->passwordInput(); ?>
	<?php
        $revokeArray = ArrayHelper::map($current_user_permissions,'item_name','item_name');
	    $allArray =ArrayHelper::map($all_permissions,'name','name');
	echo 'Remove permission s from user';
	echo $form->field($model, 'delete_permissions')->checkboxList($revokeArray)->label(false);
	echo 'Add permission to user';
	echo $form->field($model, 'add_permissions')->checkboxList($allArray)->label(false);
    ?>


    <?= $form->field($model,'updated_at')->hiddenInput(['value'=>date('Y-m-d')])->label(false); ?>
    <div class="form-group">
        <?= Html::submitButton('Update User', ['class' => 'btn btn-primary', 'name' => 'signup-button']); ?>
    </div>

    <?php ActiveForm::end();?>

</div>