backend/controllers/UserProfileController.php
<?php

namespace backend\controllers;

use common\models\Appointment;
use common\models\Clients;
use common\models\User;
use common\models\UserPersonalInfo;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use Yii;
use yii\web\UploadedFile;

class UserProfileController extends Controller
{
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['index','update'],
				'rules' => [
					[
						'actions' => ['index','update'],
						'allow' => true,
						'roles' => ['admin','clientManage']
					],
				],
			],
		];
	}
    public function actionIndex()
    {
    	$user_id =\Yii::$app->user->identity->getId();

        $user_personal_info =  UserPersonalInfo::find()->where(['user_id'=>$user_id])->one();


        return $this->render('index',['model' => $user_personal_info]);
    }

	public function actionAnalitycs()
	{
		$user_id =\Yii::$app->user->identity->getId();
		$appointment_data = Appointment::find()->where(['user_appointment_id'=>$user_id])->all();
		$client_data = Clients::find()->where(['user_id'=>$user_id])->all();

		return $this->render('analitycs',['appointment_data'=>$appointment_data,'client_data'=>$client_data]);
	}

	public function actionUpdate($id)
	{
		$model =  $this->find($id);
		$old_img = $model->avatar;
		$user_id = $model->user->id;
		if ($model->load(Yii::$app->request->post())){

            $model->avatar = UploadedFile::getInstance($model,'avatar');

           if (!empty($model->avatar)) {
	           @unlink($old_img);
                $model->avatar->saveAs('uploads/' . md5(time()) . '.' . $model->avatar->extension);
                $model->avatar = 'uploads/' . md5(time()). '.' . $model->avatar->extension;
            }else {
               $model->avatar = $old_img;
           }

           $user_email = $_POST['User']['email'];
           $user_model = User::find()->where(['id' => $user_id])->one();
           if($user_model->email !== $user_email) {
	           $user_model->email = $user_email;
	           $user_model->save();
           }
           if ($model->save()) {
	           return $this->redirect(['index']);
           }
		}
		return $this->render('update', [
			'model' => $model,
		]);
	}
	public function find($id){
		$model = UserPersonalInfo::findOne($id);
		if($model === null){
			throwException('400', 'Model not exists');
		}
		return $model;
	}



}

backend/views/user-profile/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use common\widgets\ckeditor\CKEditor;
/* @var $this yii\web\View */
/* @var $model app\models\UserPersonalInfo */
/* @var $form ActiveForm */
?>
<div class="user-profile">
	<?php $form = ActiveForm::begin(
        [ 'id'=>'user-profile-update-form',
		'enableClientValidation' => true,
		'options' => [
			'enctype'=>'multipart/form-data',
			'validateOnBlur' => true,
			'class' => 'form'
		]]); ?>
    <img src="<?php if(isset($model->avatar)){ echo Url::base(true).'/'.$model->avatar; }?>" width="120px" height="120px" style=" border-radius: 50%;">
    <?= $form->field($model, 'avatar')->fileInput();  ?>

	<?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>
	<?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'phone')->textInput(['type' => 'number']) ?>
	<?= $form->field($model, 'speciality')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'about')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'full'
    ]); ?>

    <?= $form->field($model, 'appointment_email')->checkbox() ?>

	<?= $form->field($model->user, 'email') ?>




	<div class="form-group">
		<?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
	</div>
	<?php ActiveForm::end(); ?>

</div><!-- user-profile -->

backend/views/user-profile/analitycs.php
<?php
/**
 * Created by PhpStorm.
 * User: edward
 * Date: 17.01.2019
 * Time: 12:41
 */
use common\widgets\highcharts\Highcharts;
use common\widgets\highcharts\HighchartsAsset;
HighchartsAsset::register($this)->withScripts(['highstock', 'modules/exporting', 'modules/drilldown']);
?>
<h1>
    <?php echo $this->title ='Analytics';
	$this->params['breadcrumbs'][] = $this->title;
?></h1>

<?php
$appointment_dates= array();
foreach ($appointment_data as $item){
    $date = substr($item['appointment_date_time'],0,10);
    if (isset($appointment_dates[$date]))
	    $appointment_dates[$date]++;
    else
	    $appointment_dates[$date]=1;

}
$finale_appointment_dates= array();
foreach ($appointment_dates as $date => $count){
	$finale_appointment_dates[]=[$date,$count];
}


$client_dates= array();
foreach ($client_data as $item){
	$date = substr($item['created_at'],0,10);
	if (isset($client_dates[$date]))
		$client_dates[$date]++;
	else
		$client_dates[$date]=1;

}
$finale_client_dates= array();
foreach ($client_dates as $date => $count){
	$finale_client_dates[]=[$date,$count];
}

echo Highcharts::widget([

	'options' => [
		'chart'=> ['type'=>'area'],
		'title' => ['text' => 'Clients Appointments'],
		'xAxis' => [
			 'categories'=> array_keys($appointment_dates)
		],
		'yAxis' => [
			'title' => ['text' => 'Clients Appointments']
		],
		 'plotOptions' =>[
        'area'=> [
//            'pointStart'=> 1940,
            'marker'=> [
                'enabled'=> false,
                'symbol'=> 'circle',
                'radius'=> 2,
                'states'=> [
                    'hover'=> [
                        'enabled'=> true
                    ]
                ]
            ]
        ]
    ],
		'series' => [
            [   'name'=> 'Clients',
				'data' => $finale_appointment_dates,
            ]

		],
        'credits' => ['enabled' => false],
	],
	'scripts' => [
		'highcharts-more',   // enables supplementary chart types (gauge, arearange, columnrange, etc.)
		'modules/exporting', // adds Exporting button/menu to chart
		'themes/grid'        // applies global 'grid' theme to all charts
	],

]);

echo '</br>';
echo '</br>';

echo Highcharts::widget([

	'options' => [
		'chart'=> ['type'=>'area'],
		'title' => ['text' => 'Clients Register'],
		'xAxis' => [
			'categories'=> array_keys($client_dates)
		],
		'yAxis' => [
			'title' => ['text' => 'Clients Register']
		],
		'plotOptions' =>[
			'area'=> [
//            'pointStart'=> 1940,
				'marker'=> [
					'enabled'=> false,
					'symbol'=> 'circle',
					'radius'=> 2,
					'states'=> [
						'hover'=> [
							'enabled'=> true
						]
					]
				]
			]
		],
		'series' => [
			[   'name'=> 'Clients',
				'data' => $finale_client_dates,
			]

		],
		'credits' => ['enabled' => false],
	],
	'scripts' => [
		'highcharts-more',   // enables supplementary chart types (gauge, arearange, columnrange, etc.)
		'modules/exporting', // adds Exporting button/menu to chart
		'themes/grid'        // applies global 'grid' theme to all charts
	],

]);

?>

backend/views/user-profile/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;
use yii\helpers\Html;
$this->title = 'Profile';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="main-contet-profile col-sm-12">
<!--    <div class="col-sm-2"></div>-->
    <div class="col-sm-12" style=" padding: 15px;">

        <div class="avatar-user col-sm-3">
            <img src="<?php if(isset($model->avatar)){ echo Url::base(true).'/'.$model->avatar; } else { echo Url::base(true).'/uploads/user_default.jpg';} ?>" width="220px" height="220px" style="    margin: 0 auto;
                border-radius: 50%;
                text-align: center;
                display: block;
            ">
            <br/>
            <h4 style="margin-top: 20px;font-weight: bold; text-align: center"><span><?php echo $model->first_name; ?></span>
                <span><?php echo $model->last_name; ?></span></h4>
        </div>

        <div class="info-user col-sm-8">
            <div class="col-sm-12">
                <div class="col-sm-4">
                    <span style="">Email: <?php echo $model->user['email'] ?></span>
                </div>
                <div class="col-sm-4">
                    <span style="">Phone: <?php echo $model->phone; ?></span>
                </div>
                <div class="col-sm-4">
                    <span style="">User Name: <?php echo $model->user['username'] ?></span>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="col-sm-4" style="margin-top: 40px;">
                    <span style="margin-right: 100px">Speciality: <?php echo $model->speciality ?></span>
                </div>
            </div>

        </div>
        <div class="col-sm-1" style="position: absolute;top: 0;right: 0;text-align: center; margin-top: 6px;">
	        <?php
	        echo Html::a(' Edit Profile', ['/user-profile/update','id' => $model->id], ['class' => 'btn btn-primary']);
	        ?>
        </div>
        <div class="col-sm-10" style="margin-top: 33px; border: 2px solid #cccccc; padding: 20px; margin-left: 70px;">
            <p> <span>About: <?php echo $model->about; ?></span></p></div>
    </div>
<!--    <div class="col-sm-2"></div>-->
</div>

backend/views/user-profile/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\UserPersonalInfo */

$this->title = 'Update Profile User: ' . $model->first_name;
$this->params['breadcrumbs'][] = ['label' => 'Profile User Update', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>